# GitLab CI/CD configuration for Jupyter notebook deployment
image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip/
    - venv/

stages:
  - test
  - deploy

# Optional: Test your notebook first
test_notebook:
  stage: test
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install nbconvert
    # Test that notebook runs without errors
    - jupyter nbconvert --to notebook --execute notebooks/MD_simulation.ipynb --output test_output.ipynb
  only:
    changes:
      - notebooks/*.ipynb
      - requirements.txt

# Deploy to GitLab Pages
pages:
  stage: deploy
  script:
    # Setup Python environment
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    
    # Create public directory
    - mkdir public
    
    # Method 1: Single notebook app (choose this if you have one main notebook)
    - |
      voila notebooks/MD_simulation.ipynb \
        --template=gridstack \
        --enable_nbextensions=True \
        --VoilaConfiguration.strip_sources=True \
        --VoilaConfiguration.file_whitelist="['.*\\.ipynb$', '.*\\.jpg$', '.*\\.png$', '.*\\.gif$', '.*\\.svg$', '.*\\.csv$']" \
        --static-dir public
    
    # Method 2: Multiple notebooks (uncomment if you have multiple notebooks)
    # - |
    #   for notebook in notebooks/*.ipynb; do
    #     basename=$(basename "$notebook" .ipynb)
    #     mkdir -p "public/$basename"
    #     voila "$notebook" \
    #       --template=gridstack \
    #       --enable_nbextensions=True \
    #       --VoilaConfiguration.strip_sources=True \
    #       --static-dir "public/$basename"
    #   done
    
    # Create index page for multiple notebooks
    - |
      cat > public/index.html << 'EOF'
      <!DOCTYPE html>
      <html>
      <head>
          <title>MD Simulation Notebooks</title>
          <style>
              body { font-family: Arial, sans-serif; margin: 40px; }
              .container { max-width: 800px; margin: 0 auto; }
              .notebook-link { 
                  display: block; 
                  padding: 15px; 
                  margin: 10px 0; 
                  background: #f8f9fa; 
                  border-radius: 5px; 
                  text-decoration: none; 
                  color: #333;
                  border-left: 4px solid #007bff;
              }
              .notebook-link:hover { background: #e9ecef; }
              h1 { color: #333; }
              .description { color: #666; margin-top: 5px; }
          </style>
      </head>
      <body>
          <div class="container">
              <h1>🔬 MD Simulation Interactive Notebooks</h1>
              <p>Click on a notebook below to run it interactively:</p>
              
              <a href="./MD_simulation/" class="notebook-link">
                  <strong>MD Simulation</strong>
                  <div class="description">Interactive molecular dynamics simulation with customizable parameters</div>
              </a>
              
              <!-- Add more notebook links here if you have multiple notebooks -->
              
              <hr style="margin: 30px 0;">
              <p><small>Powered by Voilà and GitLab Pages</small></p>
          </div>
      </body>
      </html>
      EOF

  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - main  # Only deploy from main branch